
const $OreProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.OreProperty');
Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.Material'); // This line is generally not needed

// Additional imports for material properties/tool properties
const $PropertyKey = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.PropertyKey');
const $RotorProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.RotorProperty');
const $IngotProperty = Java.loadClass("com.gregtechceu.gtceu.api.data.chemical.material.properties.IngotProperty");
const $ToolProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.ToolProperty');

GTCEuStartupEvents.registry('gtceu:material_icon_set', event => {
    event.create('infinity').parent(GTMaterialIconSet.SHINY)
    event.create('space_time').parent(GTMaterialIconSet.SHINY)
    event.create('infinity_catalyst').parent(GTMaterialIconSet.FINE)
    event.create('atomic_alloy').parent(GTMaterialIconSet.BRIGHT)
    event.create('cosmic_neutronium').parent(GTMaterialIconSet.BRIGHT)
    event.create('universium').parent(GTMaterialIconSet.METALLIC)
    event.create('stellar_matter').parent(GTMaterialIconSet.METALLIC)
    event.create('cosmic_matter').parent(GTMaterialIconSet.METALLIC)
    event.create('eternity').parent(GTMaterialIconSet.METALLIC)
    event.create('chrono-infinity_alloy').parent(GTMaterialIconSet.SHINY)
    event.create('solar_eclipse_alloy').parent(GTMaterialIconSet.METALLIC)
    event.create('solar_radiation_alloy').parent(GTMaterialIconSet.METALLIC)
    event.create('proto_matter').parent(GTMaterialIconSet.SHINY)
})

GTCEuStartupEvents.registry('gtceu:element', event => {
    event.create('infinity')
        .protons(168)
        .neutrons(316)
        .symbol('∞');
    event.create('crystal_matrix')
        .protons(6)
        .neutrons(6)
        .symbol('C*');
    event.create('resonant_essence')
        .protons(112)
        .neutrons(174)
        .symbol('Es↔');
    event.create('hypoxylon')
        .protons(112)
        .neutrons(174)
        .symbol('Xy');
    event.create('antimatter')
        .protons(1000)
        .neutrons(1000)
        .symbol('A');
    event.create('cosmic_neutronium')
        .neutrons(1000)
        .symbol('Ntᶜˢ');
    event.create('cosmic_tungsten')
        .neutrons(74)
        .neutrons(174)
        .symbol('Wᶜˢ');
    event.create('cosmic_titanium')
        .neutrons(22)
        .neutrons(48)
        .symbol('Tiᶜˢ');
    event.create('cosmic_iridium')
        .neutrons(77)
        .neutrons(192)
        .symbol('Irᶜˢ');
    event.create('cosmic_osmium')
        .neutrons(76)
        .neutrons(190)
        .symbol('Osᶜˢ');
    event.create('kaemite')
        .protons(142)
        .neutrons(194)
        .symbol('Ka');
    event.create('draconium')
        .protons(4043)
        .neutrons(10750)
        .symbol('Dn');
    event.create('star_matter')
        .protons(10)
        .neutrons(15)
        .symbol('Sm');
    event.create('condensed_star_matter')
        .protons(1510)
        .neutrons(2226)
        .symbol('*Sm*');
    event.create('teslarium')
        .protons(24)
        .neutrons(48)
        .symbol('Ts');
    event.create('awakened_draconium')
        .protons(61)
        .neutrons(82)
        .symbol('*Dn*');      
    event.create('chaos')
        .protons(50)
        .neutrons(75)
        .symbol('Ch');
    event.create('cosmic_matter')
        .protons(199)
        .neutrons(99)
        .symbol('CoM');
    event.create('astral_flux')
        .protons(199)
        .neutrons(399)
        .symbol('Af');
    event.create('universium')
        .symbol('Un')
        .protons(9999)
        .neutrons(9999)
    event.create('eternity')
        .symbol('Et')
        .protons(9999)
        .neutrons(9999)
    event.create('space_time')
        .symbol('SpT')
        .protons(9999)
        .neutrons(9999)
    event.create('chrono_infinity')
        .protons(168)
        .neutrons(316)
        .symbol('⧖∞')
    event.create('stellar_matter_plasma')
        .protons(168)
        .neutrons(316)
        .symbol('StM')
    event.create('resonant_naquadah')
        .symbol('Nq↔')
        .protons(174)
        .neutrons(360)
    event.create('chronon')
        .protons(238)
        .neutrons(526)
        .symbol('Cn')
    event.create('solar_eclipse_alloy')
        .protons(168)
        .neutrons(316)
        .symbol('☼');
    event.create('proto_matter')
        .protons(168)
        .neutrons(316)
        .symbol('¤');
    event.create('solar_radiation_alloy')
        .protons(168)
        .neutrons(316)
        .symbol('☼*');
        //  ₂₃₄₅₆₇₈₉₀
})


GTCEuStartupEvents.registry('gtceu:material', event => {
    
    const $IngotProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.IngotProperty');
    const $DustProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.DustProperty');
    const $BlastProperty = Java.loadClass('com.gregtechceu.gtceu.api.data.chemical.material.properties.BlastProperty');

GTMaterials.Neutronium.addFlags(GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_ROUND, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_DENSE)
GTMaterials.StainlessSteel.addFlags(GTMaterialFlags.GENERATE_DENSE)

GTMaterials.PolyvinylButyral.addFlags(GTMaterialFlags.GENERATE_FOIL)

GTMaterials.Californium.setProperty(PropertyKey.DUST, new $DustProperty());

GTMaterials.Nihonium.setProperty(PropertyKey.DUST, new $DustProperty());
GTMaterials.Nihonium.setProperty(PropertyKey.INGOT, new $IngotProperty());

GTMaterials.Thallium.setProperty(PropertyKey.DUST, new $DustProperty());
GTMaterials.Thallium.setProperty(PropertyKey.INGOT, new $IngotProperty());




    event.create('star_matter')
        .ingot().liquid()
        .element('star_matter')
        .cableProperties(GTValues.V[GTValues.IV], 128, 0, true)
        .color(0x0059ff)
    event.create('mercury_vapor')
        .liquid()
        .color(0xd7d7db)
        .element(GTElements.Hg)
    event.create('inert_life_essence')
        .liquid()
        .color(0xe0bcc3)
    event.create('raw_life_essence')
        .liquid()
        .color(0xa8979a)
    event.create('processed_life_essence')
        .liquid()
        .color(0xff7878)
    event.create('processed_naquadria_sulfate')
        .liquid()
        .color(0x82ff82)
    event.create('acidic_processed_naquadria_sulfate')
        .liquid()
        .color(0xc5ff82)
    event.create('acidic_naquadria_fuel_solution')
        .liquid()
        .color(0xc5ff82)
    event.create('impure_naquadria_fuel')
        .liquid()
        .color(0x6d9c76)
    event.create('pure_naquadria_fuel')
        .liquid()
        .color(0x426148)
        .formula('*Nq↔*', true)
    event.create('enriched_naquadria_fuel_base')
	    .liquid()
        .color(0x4d8258)
	event.create('lightly_plasmacracked_enriched_naquadria_fuel_base')
        .liquid()
        .color(0x378e49)
	event.create('severly_plasmacracked_enriched_naquadria_fuel_base')
        .liquid()
        .color(0x426148)
	event.create('enriched_naquadah_fuel_waste')
        .liquid()
        .color(0x61a870)
	event.create('light_naquadria_fuel')
        .liquid()
        .color(0x6cd482)
	event.create('treated_light_naquadria_fuel')
        .liquid()
        .color(0x72e389)
	event.create('light_naquadria_fuel_waste')
        .liquid()
        .color(0x72b27f)
	event.create('heavy_naquadria_fuel')
        .liquid()
        .color(0x4f7958)
	event.create('heavy_naquadria_fuel_waste')
        .liquid()
        .color(0x415846)
	event.create('treated_heavy_naquadria_fuel')
        .liquid()
        .color(0x6daa7a)
	event.create('super_dense_naquadria_fuel')
        .liquid()
        .color(0x224e2c)
	event.create('treated_super_dense_naquadria_fuel')
        .liquid()
        .color(0x2d703c)
	event.create('liquid_nitrogen')
        .liquid()
        .color(0x42d0d0)
        .element(GTElements.N)
	event.create('super_dense_hog')
        .liquid()
        .color(0x9b792f)
	event.create('depleted_thorium_fuel')
        .liquid()
        .color(0x9b792f)
	event.create('unstable_enriched_thorium_fuel')
        .liquid()
        .color(0x2c4022)
	event.create('lightly_plasmacracked_unstable_enriched_thorium_fuel')
        .liquid()
        .color(0x2d5519)
	event.create('severly_plasmacracked_unstable_enriched_thorium_fuel')
        .liquid()
        .color(0x153007)
	event.create('hot_stabilized_enriched_thorium_fuel')
        .liquid()
        .color(0x1b350e)
	event.create('stabilized_enriched_thorium_fuel')
        .liquid()
        .color(0x253f17)
        .formula('*Th↔*', true)
	event.create('very_unstable_hyper_enriched_thorium_fuel')
        .liquid()
        .color(0x132e04)
	event.create('hot_meta_stable_hyper_enriched_thorium_fuel')
        .liquid()
        .color(0x234d0b)
	event.create('meta_stable_hyper_enriched_thorium_fuel')
        .liquid()
        .color(0x16250d)
        .formula('*Th↔*', true)
	event.create('naquadria_fuel_mixture_mk2')
        .liquid()
        .color(0x4fad63)
	event.create('naquadria_fuel_mixture_mk3')
        .liquid()
        .color(0x348045)
	event.create('naquadria_fuel_mk2')
        .liquid()
        .color(0x1c4525)
        .formula('*Nq↔*', true)
	event.create('naquadria_fuel_mk3')
        .liquid()
        .color(0x063e13)
        .formula('*Nq↔*', true)
    event.create('naquadria_plasma')
        .plasma()
        .color(0x426148)
        .element(GTElements.Nq2)
    event.create('naquadria_plasma_mk2')
        .plasma()
        .color(0x5e8866)
        .element(GTElements.Nq2)
	event.create('naquadria_plasma_mk3')
        .plasma()
        .color(0x87bf92)
        .element(GTElements.Nq2)
	event.create('thorium_plasma')
        .plasma()
        .color(0x09170c)
        .element(GTElements.Th)
	event.create('naquadria_mk1_fuel_waste')
        .liquid()
        .color(0x2f4332)
	event.create('naquadria_mk2_fuel_waste')
        .liquid()
        .color(0x2f4934)
	event.create('naquadria_mk3_fuel_waste')
        .liquid()
        .color(0x769377)
    event.create('resonant_naquadah')
        .ingot().liquid()
        .ore(1, 1,)
        .color(0x2b3d2d)
        .element('resonant_naquadah')
        .blastTemp(9100) 
        .cableProperties(GTValues.V[GTValues.UV], 128, 2, true)
        .iconSet(GTMaterialIconSet.SHINY)
        .flags(
            GTMaterialFlags.GENERATE_PLATE,
            GTMaterialFlags.GENERATE_BOLT_SCREW,
            GTMaterialFlags.GENERATE_ROD,
            GTMaterialFlags.GENERATE_SPRING,
            GTMaterialFlags.GENERATE_SPRING_SMALL,
            GTMaterialFlags.GENERATE_FOIL,
            GTMaterialFlags.NO_SMELTING,
            GTMaterialFlags.NO_ORE_SMELTING

        )
    event.create('crystal_matrix')
        .ingot().liquid()
        .element('crystal_matrix')
        .color(0x66ffff)
        .iconSet('shiny')
        .cableProperties(GTValues.V[GTValues.UHV], 256, 0, true)
        .fluidPipeProperties(100000, 64000, true, true, true, true)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_ROTOR, GTMaterialFlags.GENERATE_DENSE);
    event.create('infinity')
        .ingot()
        .element(GTElements.get("infinity"))
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .color(0xffffff)
        .iconSet('infinity')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD,  GTMaterialFlags.GENERATE_LONG_ROD, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_ROUND, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SMALL_GEAR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_DENSE);
    event.create('infinity_catalyst')
        .dust()
        .element(GTElements.get("infinity"))
        .color(0xffffff)
        .iconSet('infinity_catalyst')
        .ore(1, 1,)

    event.create("triplatirium_235")
        .ingot().liquid()
        .components('1x uranium-235', '1x uranium', '3x platinum', '1x duranium')
        .formula('(Tr₂₃₅(U₂₃₅UPt₃Dr))', true)
        .element('triplatirium_235')
        .blastTemp(10800)
        .color(0x47ffaf)
        .iconSet('metallic')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_CENTRIFUGING, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.NO_SMELTING);

    event.create("atomic_alloy")
        .ingot()
        .components('14x californium', '1x uranium-235', '1x uranium', '3x platinum', '1x duranium')
        .formula('Cf₇(Tr₂₃₅(U₂₃₅UPt₃Dr))₀.₅₀', true)
        .blastTemp(10800)
        .color(0x513499)
        .iconSet('bright')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_ROTOR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.NO_SMELTING);

    event.create("triplatirium_sulfate")
        .liquid()
        .color(0xbff52a)
    event.create("processed_triplatirium_sulfate")
        .liquid()
        .color(0x97ba38)
    event.create("trisulfate_slurry")
        .liquid()
        .color(0xbaa238)
    event.create("cleaned_trisulfate_slurry")
        .liquid()
        .color(0xcfbd70)
    event.create("trisulfate_solution")
        .liquid()
        .color(0xa9ccc7)
    event.create("pure_trisulfate_solution")
        .liquid()
        .color(0xc3e3de)
    event.create("trisulfate_waste")
        .liquid()
        .color(0x303635)
    event.create("californium_sulfate")
        .liquid()
        .color(0x99997c)
    event.create("processed_californium_sulfate")
        .liquid()
        .color(0x7c8799)
    event.create("cleaned_californium")
        .ingot()
        .color(0xa3b2c9)
        .flags(GTMaterialFlags.GENERATE_PLATE)
        .element(GTElements.Cf)
    event.create("condensed_star_matter")
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .element('condensed_star_matter')
        .color(0xffffff)
    event.create("antimatter")
        .liquid().ingot()
        .color(0x8f34eb)
        .element('antimatter')
        .iconSet('metallic')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_ROTOR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.NO_SMELTING);
    event.create('reactable_fissioned_matter')
        .plasma()
        .color(0x270a4d)
        event.create('cosmic_neutronium')
        .ingot()
        .color(0x161616)
        .ore(1, 1,)
        .element('cosmic_neutronium')
        .iconSet('radioactive')
        .blastTemp(13000, 'highest', 2097152, 2400)
        .cableProperties(GTValues.V[GTValues.OpV], 999, 0, true)
        .flags(
            GTMaterialFlags.GENERATE_PLATE, 
            GTMaterialFlags.GENERATE_ROD, 
            GTMaterialFlags.GENERATE_GEAR, 
            GTMaterialFlags.GENERATE_FINE_WIRE,
            GTMaterialFlags.GENERATE_FRAME, 
            GTMaterialFlags.GENERATE_DENSE, 
            GTMaterialFlags.GENERATE_ROTOR, 
            GTMaterialFlags.GENERATE_BOLT_SCREW,
            GTMaterialFlags.GENERATE_SMALL_GEAR,
            GTMaterialFlags.GENERATE_ROUND,
            GTMaterialFlags.GENERATE_SPRING
        )
    event.create('heavy_duty_alloy_t1')
        .ingot()
        .color(0x333e47)
        .blastTemp(10000)
        .cableProperties(GTValues.V[GTValues.EV], 32, 0, true)
        .iconSet('metallic')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.NO_SMELTING)
    event.create('heavy_duty_alloy_t2')
        .ingot()
        .color(0xfbff00)
        .blastTemp(10000)
        .iconSet('metallic')
        .cableProperties(GTValues.V[GTValues.LuV], 64, 0, true)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.NO_SMELTING)
    event.create('heavy_duty_alloy_t3')
        .ingot()
        .color(0xb2a7d4)
        .blastTemp(10000)
        .cableProperties(GTValues.V[GTValues.UHV], 1024, 0, true)
        .iconSet('metallic')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.NO_SMELTING)
        event.create('heavy_duty_alloy_t4')
        .ingot().liquid()
        .color(0x17e0ff)
        .cableProperties(GTValues.V[GTValues.UXV], 24, 0, true)
        .iconSet('metallic')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create('mixed_alloy')
        .ingot()
        .color(0xe8c492)
        .iconSet('metallic')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create('energetic_bronze')
        .ingot()
        .color(0xD68A58)
        .iconSet('metallic')
        .flags(GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create('kaemite')
        .ingot().liquid()
        .color(0x00cfff)
        .ore(1, 1,)
        .element('kaemite')
        .iconSet('metallic')
        .cableProperties(GTValues.V[GTValues.UEV], 32, 0, true)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.GENERATE_FRAME)
    event.create('acidic_venus_residue')
        .liquid()
        .color(0x944e09)
    event.create('resonant_essence_residue')
        .liquid()
        .color(0x099409)
    event.create('resonant_essence')
        .ingot().liquid()
        .color(0x8ceb34)
        .ore(1, 1,)
        .blastTemp(12000)
        .element('resonant_essence')
        .iconSet('bright')
        .cableProperties(GTValues.V[GTValues.UEV], 256, 0, true)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_ROTOR, GTMaterialFlags.GENERATE_BOLT_SCREW)
    event.create('energized_superconductor')
        .ingot()
        .color(0xffa600)
        .iconSet('bright')
        .cableProperties(GTValues.V[GTValues.LV], 4, 0, true)
    event.create('hsc_superconductor')
        .ingot()
        .color(0x3f403d)
        .iconSet('bright')
        .cableProperties(GTValues.V[GTValues.MV], 8, 0, true)
    event.create('platium_superconductor')
        .ingot()
        .color(0xff0000)
        .iconSet('bright')
        .cableProperties(GTValues.V[GTValues.HV], 16, 0, true)
    event.create('tilrunum_superconductor')
        .ingot()
        .color(0xd1dced)
        .iconSet('bright')
        .cableProperties(GTValues.V[GTValues.EV], 32, 0, true)
    event.create('crystal_superconductor')
        .ingot()
        .color(0x6200ff)
        .iconSet('bright')
        .cableProperties(GTValues.V[GTValues.ZPM], 32, 0, true)
    event.create('teslarium')
        .ingot()
        .color(0x4800bd)
        .iconSet('shiny')
        .element('teslarium')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE)

        // B A C T E R I A L   S T U F F

        event.create("raw_bacterial_dna")
        .liquid()
        .color(0xf595eb)
        event.create("overgrown_bacterial_dna")
        .liquid()
        .color(0x95f5d0)
        event.create("panaeolus_cyanescens")
        .liquid()
        .color(0x3a5963)
        event.create("streptomyces_coelicolor")
        .liquid()
        .color(0x3a6353)
        event.create("pcr_its1_its2")
        .liquid()
        .color(0xdb393e)
        event.create("streptomyces_peucetius")
        .liquid()
        .color(0xdb3962)
        event.create("taq_polymerase")
        .liquid()
        .color(0x082b06)
        event.create("doxorubicin")
        .liquid()
        .color(0x062b18)
        event.create("phage")
        .liquid()
        .color(0x148f50)
        event.create("bacterium")
        .liquid()
        .color(0xe310b9)
        event.create("bacterial_dna")
        .liquid()
        .color(0xff0066)
        event.create("mycena_hypsizyga")
        .liquid()
        .color(0x00ff11)
        event.create("stropharic_hypoxylon")
        .liquid()
        .color(0x7a64f5)
        event.create("hypoxylon")
        .liquid().ingot()
        .color(0x7c65fc)
        .element('hypoxylon')
        .iconSet('bright')
        .cableProperties(GTValues.V[GTValues.UXV], 64, 2, true)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_ROTOR, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.NO_SMELTING, GTMaterialFlags.NO_ORE_SMELTING)
    
    event.create('draconium')
        .ingot().liquid()
        .ore(1, 1,)
        .color(0x7A42AE)
        .element('draconium')
        .iconSet('metallic')
        .flags(
            GTMaterialFlags.GENERATE_PLATE, 
            GTMaterialFlags.GENERATE_ROD, 
            GTMaterialFlags.GENERATE_GEAR, 
            GTMaterialFlags.GENERATE_FINE_WIRE,
            GTMaterialFlags.GENERATE_FRAME, 
            GTMaterialFlags.GENERATE_DENSE, 
            GTMaterialFlags.GENERATE_ROTOR, 
            GTMaterialFlags.GENERATE_BOLT_SCREW,
            GTMaterialFlags.GENERATE_SMALL_GEAR,
            GTMaterialFlags.GENERATE_LONG_ROD,
            GTMaterialFlags.GENERATE_LENS,
            GTMaterialFlags.GENERATE_ROUND,
        )
        .blastTemp(13000, 'highest', 2097152, 200)
        .cableProperties(GTValues.V[GTValues.UEV], 8, 4, false)
    
    event.create('awakened_draconium')
        .ingot().liquid()
        .ore(1, 1,)
        .color(0xFF6A00)
        .element('awakened_draconium')
        .iconSet('shiny')
        .flags(
            GTMaterialFlags.GENERATE_PLATE, 
            GTMaterialFlags.GENERATE_ROD, 
            GTMaterialFlags.GENERATE_GEAR, 
            GTMaterialFlags.GENERATE_FINE_WIRE,
            GTMaterialFlags.GENERATE_FRAME, 
            GTMaterialFlags.GENERATE_DENSE, 
            GTMaterialFlags.GENERATE_ROTOR, 
            GTMaterialFlags.GENERATE_BOLT_SCREW,
            GTMaterialFlags.GENERATE_SMALL_GEAR,
            GTMaterialFlags.GENERATE_LONG_ROD,
            GTMaterialFlags.GENERATE_ROUND
        )
        .blastTemp(15000, 'highest', 134217728, 3400)
        .cableProperties(GTValues.V[GTValues.UIV], 32, 4, false)
    
    event.create('californite')
        .ingot().liquid()
        .components('19x californium', '1x silicon', '152x iridium', '64x osmium', '448x chromium', '288x neutronium', '48x lead', '16x platinum', '8x radon')
        .formula('Cf₁₉(Si(Ir₁₉Os₈(Nc(Cr₇Nt₄)₈)(PbR(Pb₆Pt₂Rn₁))₁)₈)', true)
        .color(0xa0b0bd).secondaryColor(0x232020)
        .iconSet('radioactive')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.GENERATE_DENSE)
    event.create('stabilized_iridium')
        .ingot().liquid()
        .components('19x iridium', '8x osmium', '56x chromium', '36x neutronium', '6x lead', '2x platinum', '1x radon')
        .formula('Ir₁₉Os₈(Nc(Cr₇Nt₄)₈)(PbR(Pb₆Pt₂Rn))₁)', true)
        .color(0x9deafa).secondaryColor(0x232020)
        .iconSet('radioactive')
        .blastTemp(13000, 'highest', 2097152, 200)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_GEAR)
    event.create('magnetic_stabilized_iridium')
        .ingot()
        .formula('Ir₁₉Os₈(Nc(Cr₇Nt₄)₈)(PbR(Pb₆Pt₂Rn))₁)', true)
        .color(0x9deafa).secondaryColor(0x232020)
        .iconSet(GTMaterialIconSet.MAGNETIC)
        .ingotSmeltInto(GTMaterials.get('stabilized_iridium'))
        .arcSmeltInto(GTMaterials.get('stabilized_iridium'))
        .macerateInto(GTMaterials.get('stabilized_iridium'))
        .flags(GTMaterialFlags.GENERATE_LONG_ROD, GTMaterialFlags.IS_MAGNETIC)

    event.create('neutronic_chromite')
        .ingot()
        .components('7x chromium', '4x neutronium')
        .formula('Nc(Cr₇Nt₄)', true)
        .color(0xf5c6da).secondaryColor(0x232020)
        .iconSet('radioactive')
        .blastTemp(10500, 'highest', 524288, 900)
        .flags(GTMaterialFlags.GENERATE_PLATE)
    event.create('radium_infused_lead')
        .ingot()
        .components('6x lead', '2x platinum', '1x radon')
        .formula('PbR(Pb₆Pt₂Rn)', true)
        .color(0x52303e)
        .iconSet('shiny')
        .blastTemp(3500, 'highest', 2048, 900)
        .flags(GTMaterialFlags.GENERATE_PLATE)
    event.create('chaos')
        .gem().liquid()
        .ore(1, 1,)
        .element('chaos')
        .cableProperties(GTValues.V[GTValues.UIV], 512, 0, true)
        .color(0x010005)
        .iconSet('dull')
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_LENS, GTMaterialFlags.GENERATE_DENSE)
/// P O L Y M E R   S T U F F

    event.create('neoprene')
        .liquid(313).ingot().polymer()
        .color(0xFFECB3)
        .components('4x carbon', '5x hydrogen', '1x chlorine')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.NO_SMELTING)  
        .iconSet('bright')
    event.create('xlpe')
        .liquid(408).ingot().polymer()
        .color(0xebeae8)
        .components('2x carbon', '4x hydrogen')
        .formula("(C₂H₄)↔", true)
        .iconSet('bright')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_RING)
    event.create('peek')
        .liquid(408).ingot().polymer()
        .color(0x382e27)
        .components('19x carbon', '12x hydrogen', '3x oxygen')
        .iconSet('bright')
        .fluidPipeProperties(616, 50000, true, true, true, false)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_FRAME)
    event.create('carbon_nanotubes')
        .ingot()
        .color(0x050505)
        .components('64x carbon')
        .formula("C⁺", true)
        .iconSet('bright')
        .flags(GTMaterialFlags.NO_SMELTING, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create('kevlar')
        .ingot()
        .color(0xd7d952)
        .components('14x carbon', '10x hydrogen', '2x nitrogen', '2x oxygen')
        .iconSet('dull')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.NO_SMELTING, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_FINE_WIRE)
    event.create('zylon')
        .ingot()
        .color(0xd1a72a)
        .components('14x carbon', '6x hydrogen', '2x nitrogen', '2x oxygen')
        .iconSet('bright')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.NO_SMELTING, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_RING, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_FINE_WIRE)

	event.create('sbr_emulsion')
		.liquid(353)
		.color(0xFFECB3)
		.formula('C₆H₆·C₄H₆', true)
	event.create('trichlorosilane')
		.liquid(305) 
		.color(0xF5F5F5)
		.components('1x silicon', '1x hydrogen', '3x chlorine')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
	event.create('pure_trichlorosilane')
		.liquid(305) 
		.color(0xFFFFFF)
		.components('1x silicon', '1x hydrogen', '3x chlorine')
	event.create('silicone_prepolymer')
		.liquid(473) 
		.color(0xEEEEEE)
		.formula('(C₂H₆OSi)ₙ', true)
    event.create('plasticizer')
        .liquid(393) 
        .color(0xFFF59D)
        .components('12x carbon', '22x hydrogen', '4x oxygen')
    event.create('hydrazobenzene')
        .liquid(399)
        .color(0xFFD700)
        .components('12x carbon', '12x hydrogen', '2x nitrogen')
    event.create('diacetyl_benzidine')
        .liquid(533)
        .color(0xF5F5DC)
        .formula('(C₂H₄NO)₂(C₆H₄)₂', true)
    event.create('dinitro_diacetyl_benzidine')
        .liquid(518)
        .color(0xDAA520)
        .formula('(C₂H₄NO)₂(C₆H₃)₂(NO₂)₂', true)
    event.create('dinitro_benzidine')
        .liquid(523)
        .color(0x9C640C)
        .formula('(NH₂)₂(C₆H₃)₂(NO₂)₂', true)
    event.create('sodium_acetate')
        .dust()
        .color(0xDEDEDE)
        .components('2x carbon', '3x hydrogen', '1x sodium', '2x oxygen')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('calcium_carbide')
        .dust()
        .color(0x6b6a66)
        .components('1x calcium', '2x carbon')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('acetylene')
        .gas(467)
        .color(0xabaaa7)
        .components('2x carbon', '2x hydrogen')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('cuprous_chloride')
        .dust()
        .color(0x4A3C78)
        .components('1x copper', '1x chlorine')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('vinylacetylene')
        .liquid(273)
        .color(0xFFAB91)
        .components('4x carbon', '4x hydrogen')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('chloroprene')
        .liquid(332)
        .color(0xFFCC80)
        .components('4x carbon', '5x hydrogen', '1x chlorine')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('neoprene_latex')
        .liquid(313) 
        .color(0xc2b17e)
        .element('neoprene') 
    event.create('raw_neoprene')
        .dust()
        .color(0xFFECB3)
        .element('neoprene') 
    event.create('cumene_hydroperoxide')
        .liquid(388)
        .color(0xFFF59D)
        .components('9x carbon', '12x hydrogen', '2x oxygen')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('dicumyl_peroxide')
        .liquid(353)
        .color(0xF5F5F5)
        .components('18x carbon', '22x hydrogen', '2x oxygen')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('pe_peroxide_mixture')
        .liquid(473)
        .color(0xE0E0E0)
        .formula('C₂H₄·C₁₈H₂₂O₂', true)
    event.create('thermal_treated_xlpe')
        .ingot()
        .color(0xE0E0E0)
        .components('4x carbon', '2x hydrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION, GTMaterialFlags.GENERATE_PLATE)
    event.create('antimony_pentafluoride')
        .dust()
        .color(0xE6E6FA)
        .components('1x antimony', '5x fluorine')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('aluminium_chloride')
        .dust()
        .color(0xE6E6FA)
        .components('1x aluminium', '3x chlorine')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('fluorobenzene')
        .liquid(358)
        .color(0xFFFF00)
        .components('6x carbon', '5x hydrogen', '1x fluorine')
    event.create('phosgene')
        .liquid(280)
        .color(0xE6E6FA)
        .components('1x carbon', '1x oxygen', '2x chlorine')
    event.create('thionyl_chloride')
        .liquid(349)
        .color(0xFFFFE0)
        .components('1x sulfur', '1x oxygen', '2x chlorine')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('benzenesulfonic_acid')
        .dust()
        .color(0xE6E6FA)
        .components('6x carbon', '6x hydrogen', '3x oxygen', '1x sulfur')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('benzenesulfonyl_chloride')
        .liquid(291)
        .color(0xffff7a)
        .components('6x carbon', '5x hydrogen', '1x chlorine', '2x oxygen', '1x sulfur')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('diphenyl_sulfone')
        .liquid(428) 
        .color(0xF5F5F5)
        .components('12x carbon', '10x hydrogen', '1x sulfur', '2x oxygen')
        .formula('(C₆H₅)₂SO₂', true)
    event.create('diluted_diphenyl_sulfone')
        .liquid(428) 
        .color(0xc7c5c5)
        .element('diphenyl_sulfone') 
    event.create('difluorobenzophenone')
        .liquid(593)
        .color(0xFFFF00)
        .components('13x carbon', '8x hydrogen', '2x fluorine', '1x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('purified_difluorobenzophenone')
        .dust()
        .color(0xFFEB3B)
        .components('13x carbon', '8x hydrogen', '2x fluorine', '1x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('iron_sulfate')
        .dust()
        .color(0x94d490)
        .components('1x iron', '1x sulfur', '4x oxygen')
    event.create('hydroquinone_solution')
        .liquid(333) 
        .color(0x880E4F)
        .components('6x carbon', '6x hydrogen', '2x oxygen')
    event.create('hydroquinone')
        .dust()
        .color(0xed6db1)
        .components('6x carbon', '6x hydrogen', '2x oxygen')
    event.create('butynediol')
        .dust()
        .color(0xd2dec5)
        .components('4x carbon', '6x hydrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('butanediol')
        .liquid(293)
        .color(0xa8b59a)
        .components('4x carbon', '10x hydrogen', '2x oxygen')
    event.create('butenediol')
        .dust()
        .color(0xa8b59a)
        .components('4x carbon', '8x hydrogen', '2x oxygen')
    event.create('butyrolactone')
        .liquid(229)
        .color(0xe8edcc)
        .components('4x carbon', '6x hydrogen', '2x oxygen')
    event.create('pyrrolidone')
        .liquid(298)
        .color(0xe4f5a9)
        .components('4x carbon', '7x hydrogen', '1x nitrogen', '1x oxygen')
    event.create('n_methyl_pyrrolidone')
        .liquid(249)
        .color(0xf1f743)
        .components('5x carbon', '9x hydrogen', '1x nitrogen', '1x oxygen')
    event.create('diluted_n_methyl_pyrrolidone')
        .liquid(249)
        .color(0xc0c299)
        .components('5x carbon', '9x hydrogen', '1x nitrogen', '1x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('raw_peek_solution')
        .liquid(593)
        .color(0x382a1f)
        .components('19x carbon', '12x hydrogen', '3x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('raw_peek')
        .dust()
        .color(0x382a1f)
        .components('19x carbon', '12x hydrogen', '3x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('enriched_carbon_slurry')
        .liquid(4600)
        .color(0x050505)
    event.create('plasmacracked_carbon_slurry')
        .liquid(5000)
        .color(0x171717)
    event.create('enriched_carbon_solution')
        .liquid(1250)
        .color(0x242323)
    event.create('carbon_nanotubes_doped_aluminium_chloride')
        .dust()
        .color(0x48666e)
        .secondaryColor(0x0e1112)
    event.create('raw_carbon_nanotubes_solution')
        .liquid()
        .color(0x0d0d0d)
    event.create('wet_carbon_nanotubes')
        .dust()
        .color(0x0f0f0f)
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.DISABLE_MATERIAL_RECIPES)
    event.create('deep_water')
        .liquid(300)
        .color(0x01076e)
        .formula('H₂O?', true)
    event.create('filtered_deep_water')
        .liquid(300)
        .color(0x0e17a1)
        .formula('H₂O?', true)
    event.create('concentrated_heavy_brine')
        .liquid(293)
        .color(0x63230a)
    event.create('super_concentrated_heavy_brine')
        .liquid(274)
        .color(0x63230a)
    event.create('acidified_heavy_brine')
        .liquid(293)
        .color(0xbd4e24)
    event.create('depleted_heavy_brine')
        .liquid(293)
        .color(0x52372d)
    event.create('demineralized_heavy_brine')
        .liquid(293)
        .color(0x362b28)
    event.create('heavy_salts_waste')
        .liquid(293)
        .color(0x262b09)
    event.create('iodide_loaded_resin')
        .ingot()
        .color(0x87752e)
        .flags(GTMaterialFlags.GENERATE_PLATE)
    event.create('sodium_iodide_solution')
        .liquid(293)
        .color(0x3a0f96)
    event.create('iodine_suspension')
        .liquid(293)
        .color(0x3f2675)
    event.create('alumina')
        .dust()
        .color(0xb4c6cf)
        .components('2x aluminium', '3x oxygen')
    event.create('cobalt_alumina_catalyst')
        .dust()
        .color(0x1152a8)
        .components('2x aluminium', '4x oxygen', '1x cobalt')
        .formula('CoO·Al₂O₃', true)
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('activated_cobalt_alumina_catalyst')
        .dust()
        .color(0x4a7f96)
        .components('2x aluminium', '4x oxygen', '1x cobalt')
        .formula('CoO·Al₂O₃', true)
    event.create('nickel_bromide')
        .dust()
        .color(0x2F4F4F)
        .components('5x nickel', '2x boron')
    event.create('manganese_sulfate')
        .dust()
        .color(0xbda0bb)
        .components('1x manganese', '1x sulfur', '4x oxygen')
    event.create('manganese_carbonate')
        .dust()
        .color(0xD3D3D3)
        .components('1x manganese', '1x carbon', '3x oxygen')
    event.create('manganese_acetate')
        .dust()
        .color(0x2F4F4F)
        .components('1x manganese', '4x carbon', '6x hydrogen', '3x oxygen')
    event.create('propionaldehyde')
        .liquid(322) 
        .color(0xFFECB3)
        .components('3x carbon', '6x hydrogen', '1x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('propionic_acid')
        .liquid(414) 
        .color(0xF5F5F5)
        .components('3x carbon', '6x hydrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('propylamine')
        .liquid(321)
        .color(0xE1F5FE)
        .components('3x carbon', '9x hydrogen', '1x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('sodium_cyanide')
        .dust()
        .color(0xe8e8e8)
        .components('1x sodium', '1x carbon', '1x nitrogen')
    event.create('hydrazine_sulfate')
        .dust()
        .color(0xf0f0f0)
        .components('2x nitrogen', '6x hydrogen', '1x sulfur', '4x oxygen')
    event.create('acetone_cyanohydrin')
        .liquid(367)
        .color(0xe0ebb7)
        .components('4x carbon', '7x hydrogen', '1x nitrogen', '1x oxygen')
    event.create('isobutyramide')
        .liquid(367)
        .color(0xe0ebb7)
        .components('8x carbon', '14x hydrogen', '4x nitrogen')
        .formula('((CH₃)₂C(CN))₂N₂H₂', true)
    event.create('azo_isobutyronitrile')
        .dust()
        .color(0xd0d1cd)
        .components('8x carbon', '12x hydrogen', '4x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION) 
    event.create('tripropylamine')
        .liquid(403) 
        .color(0xF3E5F5)
        .components('9x carbon', '21x hydrogen', '1x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('hydrogen_bromide')
        .gas(206)
        .color(0xeb823d)
        .components('1x hydrogen', '1x bromine')
    event.create('bromopropane')
        .liquid(344)
        .color(0xFFCC80)
        .components('3x carbon', '7x hydrogen', '1x bromine')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('tetrapropylammonium_bromide_solution')
        .liquid(344)
        .color(0x99914e)
        .formula('(C₃H₇)₄NBr', true)
    event.create('crude_tetrapropylammonium_bromide')
        .dust()
        .color(0xFFF59D)
        .components('12x carbon', '28x hydrogen', '1x nitrogen', '1x bromine')
        .formula('(C₃H₇)₄NBr', true)
    event.create('tetrapropylammonium_bromide')
        .dust()
        .color(0xe0d255)
        .element('tetrapropylammonium_bromide')
    event.create('diluted_ethanol')
        .liquid(325)
        .color(0xab7055)
        .components('2x carbon', '6x hydrogen', '1x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('sodium_aluminate')
        .dust()
        .color(0xf7f5bc)
        .components('1x sodium', '1x aluminium', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('zsm_5_solution')
        .liquid(325)
        .color(0x66853e)
        .element('zsm_5')
        .formula('Na₁₈Al₁₈Si₇₄O₁₉₂·16H₂O', true)
    event.create('zsm_5')
        .dust()
        .color(0x61961b)
        .formula('Na₁₈Al₁₈Si₇₄O₁₉₂·16H₂O', true)
    event.create('plasmacracked_light_fuel')
        .liquid(325)
        .color(0xd6c30f)
    event.create('plasmacracked_naphtha')
        .liquid(325)
        .color(0xd9cf75)
    event.create('plasmacracked_heavy_fuel')
        .liquid(325)
        .color(0xfcf6bb)
    event.create('cyclopentadiene')
        .liquid(312)
        .color(0xFFF8DC)
        .components('5x carbon', '6x hydrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('sodium_hypochlorite')
        .dust()
        .color(0xdedad1)
        .components('1x sodium', '1x oxygen', '1x chlorine')
    event.create('chlorocyclopentane')
        .liquid(305)
        .color(0x804541)
        .components('5x carbon', '2x hydrogen', '8x chlorine')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('hexachlorocyclopentadiene')
        .liquid(305)
        .color(0xe9eb7f)
        .components('5x carbon', '6x chlorine')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('endosulfate')
        .dust()
        .color(0x4a391d)
        .components('9x carbon', '6x hydrogen', '6x chlorine', '3x oxygen', '1x sulfur')
    event.create('mixed_xylenes')
        .liquid(325)
        .color(0xf2f1e6)
    event.create('p_xylene')
        .liquid(325)
        .color(0xfffcd9)
        .components('8x carbon', '10x hydrogen')
    event.create('m_xylene')
        .liquid(325)
        .color(0xfffcd9)
        .components('8x carbon', '10x hydrogen')
    event.create('o_xylene')
        .liquid(325)
        .color(0xfffcd9)
        .components('8x carbon', '10x hydrogen')
    event.create('barium_chloride')
        .dust()
        .color(0xededed)
        .components('1x barium', '2x chlorine')
    event.create('potassium_manganate')
        .dust()
        .color(0x16a850)
        .components('2x potassium', '1x manganese', '4x oxygen')
    event.create('barium_manganate')
        .dust()
        .color(0x004D40)
        .components('1x barium', '1x manganese', '4x oxygen')
    event.create('barium_permanganate')
        .dust()
        .color(0x4B0082)
        .components('1x barium', '2x manganese', '8x oxygen')
    event.create('barium_sulfate')
        .dust()
        .color(0xcbccc2)
        .components('1x barium', '1x sulfur', '4x oxygen')
    event.create('cobalt_sulfate')
        .dust()
        .color(0x2F4F4F)
        .components('1x cobalt', '1x sulfur', '4x oxygen')
    event.create('cobalt_permanganate_solution')
        .liquid()
        .color(0x8B008B)
    event.create('cobalt_permanganate')
        .dust()
        .color(0x8B008B)
        .components('1x cobalt', '2x manganese', '8x oxygen')
    event.create('terephthalic_acid_slurry')
        .liquid(468)
        .color(0xcbf7ad)
    event.create('crude_terephthalic_acid')
        .dust()
        .color(0xecf5e6)
        .components('8x carbon', '6x hydrogen', '4x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('terephthalic_acid')
        .dust()
        .color(0xF5F5F5)
        .components('8x carbon', '6x hydrogen', '4x oxygen')
    event.create('terephthaloyl_chloride')
        .liquid(536) 
        .color(0xFFF59D)
        .components('8x carbon', '4x hydrogen', '2x chlorine', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('copper_sulfate')
        .dust() 
        .color(0x2828d1)
        .components('1x copper', '1x sulfur', '4x oxygen') 
    event.create('hydro_ammonia_copper_chromate')
        .dust() 
        .color(0x228B22)
        .components('1x copper', '5x hydrogen', '5x oxygen', '1x nitrogen', '1x chromium')
        .formula('Cu(OH)NH₄CrO₄', true)
   event.create('ammonium_sulfate')
        .dust() 
        .color(0xc9c9f2)
        .components('2x nitrogen', '8x hydrogen', '1x sulfur', '4x oxygen') 
    event.create('copper_chromite')
        .dust() 
        .color(0xd4af5f)
        .components('2x copper', '2x chromium', '5x oxygen') 
    event.create('p_nitroaniline')
        .dust() 
        .color(0xd4af5f)
        .components('6x carbon', '6x hydrogen', '2x nitrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)    
    event.create('p_phenylenediamine_solution')
        .liquid(413)
        .color(0x4A148C)
        .components('6x carbon', '8x hydrogen', '2x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)   
    event.create('p_phenylenediamine')
        .liquid(413)
        .color(0x5409b0)
        .components('6x carbon', '8x hydrogen', '2x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)   
    event.create('kevlar_polymer_solution')
        .liquid(278)
        .color(0x7B1FA2)
        .components('14x carbon', '10x hydrogen', '2x nitrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('degassed_kevlar_solution')
        .liquid(273)
        .color(0x7B1FA2)
        .components('14x carbon', '10x hydrogen', '2x nitrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)   
    event.create('meta_stable_molten_kevlar')
        .liquid(666)
        .color(0xd6d93d)
        .components('14x carbon', '10x hydrogen', '2x nitrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)   
    event.create('triethylaluminium')
        .liquid(390)
        .color(0x807745)
        .components('1x aluminium', '6x carbon', '15x hydrogen')
        .formula('Al(C₂H₅)₃', true)
    event.create('carbon_sulfide')
        .liquid(318)
        .color(0xe0d077)
        .components('1x carbon', '2x sulfur')
    event.create('sodium_dimethyldithiocarbamate')
        .dust()
        .color(0xf5e484)
        .components('3x carbon', '6x hydrogen', '1x nitrogen', '2x sulfur', '1x sodium')
        .formula('(CH₃)₂NCS₂Na', true)
    event.create('tetramethylthiuramdisulfide')
        .dust()
        .color(0xe8cf41)
        .formula('(CH₃)₄(NCS₂)₂', true)
        .components('6x carbon', '12x hydrogen', '2x nitrogen', '4x sulfur')
    event.create('tetramethylthiuramdisulfide_solution')
        .liquid()
        .color(0xd6c565)
        .formula('(CH₃)₄(NCS₂)₂·H₂O', true)
    event.create('cocoa_oil')
        .liquid()
        .color(0x40250f)
    event.create('stearic_acid')
        .dust()
        .color(0xdbce9c)
        .components('18x carbon', '36x hydrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)  
    event.create('oleic_acid')
        .liquid()
        .color(0xb8c991)
        .components('18x carbon', '34x hydrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('plasmacracked_coal_tar')
        .liquid(323)
        .color(0x1f1f1f)
    event.create('pyridine_bases')
        .liquid(373)
        .color(0xF5F5F5)
    event.create('pyridine_sulfate_solution')
        .liquid(333)
        .color(0xF5F5F5)
        .formula('C₅H₅N·H₂SO₄', true)
    event.create('crude_pyridine')
        .liquid(383)
        .color(0xE0E0E0)
        .components('5x carbon', '5x hydrogen', '1x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('acetaldehyde')
        .gas(297)
        .color(0x9e4c4c)
        .components('2x carbon', '4x hydrogen', '1x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('synthetic_pyridine_mixture')
        .liquid(354)
        .color(0xbf8d49)
    event.create('crude_synthetic_pyridine')
        .liquid(383)
        .color(0xcfc7bc)
        .components('5x carbon', '5x hydrogen', '1x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
     event.create('technical_pyridine_mixture')
        .liquid(473)
        .color(0xFFECB3)
        .components('5x carbon', '5x hydrogen', '1x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('dry_technical_pyridine')
        .liquid(393)
        .color(0xBCAAA4)
        .components('5x carbon', '5x hydrogen', '1x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('water_toluene_azeotrope')
        .liquid(393)
        .color(0x5e2b2b)
    event.create('pure_pyridine')
        .liquid(388)
        .color(0x9E9E9E)
        .components('5x carbon', '5x hydrogen', '1x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('picoline')
        .dust()
        .color(0xa8d15c)
        .components('6x carbon', '7x hydrogen', '1x nitrogen')
    event.create('lutidine')
        .liquid(388)
        .color(0xa8bd66)
        .components('7x carbon', '9x hydrogen', '1x nitrogen')
    event.create('chloropyridine_solution')
        .liquid(388)
        .color(0x867e8c)
    event.create('chloropyridine')
        .liquid(388)
        .color(0xd2ff1c)
        .components('5x carbon', '4x hydrogen', '1x chlorine', '1x nitrogen')
    event.create('diethyl_ether')
        .liquid()
        .color(0xb8420b)
        .components('4x carbon', '10x hydrogen', '1x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('dichloropyridine')
        .dust()
        .color(0xbdafa6)
        .components('5x carbon', '3x hydrogen', '2x chlorine', '1x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('2-6_bischloromagnesiopyridine')
        .liquid()
        .color(0xF0E68C)
        .components('5x carbon', '3x hydrogen', '2x chlorine', '2x magnesium', '1x nitrogen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('magnesium_pyridine_2-6_dicarboxylate')
        .dust()
        .color(0xc7c4a9)
        .components('7x carbon', '3x hydrogen', '1x magnesium', '1x nitrogen', '4x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('picolinic_acid_slurry')
        .liquid()
        .color(0x8e5999)
    event.create('potassium_permanganate')
        .dust()
        .color(0xda12a)
        .components('1x potassium', '1x manganese', '4x oxygen')
    event.create('potassium_dipicolinate')
        .dust()
        .color(0x6b898c)
        .components('7x carbon', '3x hydrogen', '2x potassium', '1x nitrogen', '4x oxygen')
    event.create('picolinic_acid')
        .dust()
        .color(0xb354c7)
        .components('6x carbon', '5x hydrogen', '1x nitrogen', '2x oxygen')
    event.create('dipicolinic_acid')
        .dust()
        .color(0xf5f5f5)
        .components('7x carbon', '5x hydrogen', '1x nitrogen', '4x oxygen')
    event.create('phosphorus_trichloride')
        .liquid(340) 
        .color(0xcf923e)
        .components('1x phosphorus', '3x chlorine')
    event.create('phosphorus_pentachloride')
        .dust()
        .color(0xcee38f)
        .components('1x phosphorus', '5x chlorine')
    event.create('phosphorus_oxychloride')
        .liquid(370) 
        .color(0xbae340)
        .components('1x phosphorus', '1x oxygen', '3x chlorine')
    event.create('dipicolinyl_dichloride_solution')
        .liquid()
        .color(0xbf9c71)
        .components('6x carbon', '3x hydrogen', '2x chlorine', '1x nitrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('dipicolinyl_dichloride')
        .dust()
        .color(0xdbbf9c)
        .components('6x carbon', '3x hydrogen', '2x chlorine', '1x nitrogen', '2x oxygen')
    event.create('pentose_enriched_biomass')
        .liquid()
        .color(0x5c4612)
    event.create('xylose')
        .liquid()
        .color(0x82c282)
        .components('5x carbon', '10x hydrogen', '5x oxygen')
    event.create('furfural')
        .liquid(400)
        .color(0x706754)
        .components('5x carbon', '4x hydrogen', '2x oxygen')
    event.create('fumaric_acid')
        .dust()
        .color(0xccd1a1)
        .components('4x carbon', '4x hydrogen', '4x oxygen')
    event.create('diiminosuccinonitrile')
        .liquid()
        .color(0x37496b)
        .components('4x carbon', '2x hydrogen', '4x nitrogen')
    event.create('pyrazine')
        .liquid(327)
        .color(0x657799)
        .components('4x carbon', '4x hydrogen', '2x nitrogen')
    event.create('pyrazine_dicarboxylic_acid')
        .dust()
        .color(0x82c282)
        .components('6x carbon', '4x hydrogen', '2x nitrogen', '4x oxygen')
    event.create('pyrazine_dicarbonyl_dichloride')
        .liquid()
        .color(0x82c282)
        .components('6x carbon', '2x hydrogen', '2x chlorine', '2x nitrogen', '2x oxygen')
    event.create('pyrophosphoric_acid')
        .liquid(313) 
        .color(0xd5de35)
        .components('4x hydrogen', '2x phosphorus', '7x oxygen')
    event.create('triphosphoric_acid')
        .liquid(313) 
        .color(0xfafa3e)
        .components('5x hydrogen', '3x phosphorus', '10x oxygen')
    event.create('tetraphosphoric_acid')
        .liquid(313) 
        .color(0xecf719)
        .components('6x hydrogen', '4x phosphorus', '13x oxygen')
    event.create('zylon_polymer_solution')
        .liquid(453)
        .color(0x7B1FA2)
        .components('14x carbon', '6x hydrogen', '2x nitrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('degassed_zylon_solution')
        .liquid(429)
        .color(0xc96ef0)
        .components('14x carbon', '6x hydrogen', '2x nitrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('treated_zylon_polymer_solution')
        .liquid(444)
        .color(0xc2a634)
        .components('14x carbon', '6x hydrogen', '2x nitrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('meta_stable_molten_zylon')
        .liquid(666)
        .color(0xd1af24)
        .components('14x carbon', '6x hydrogen', '2x nitrogen', '2x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

/// P C B Stuff

    event.create('nano_diamond')
        .gem()
        .color(0xc2eced)
        .iconSet('diamond')
        .element('carbon')
        .formula('C⁺⁺')
    event.create('activated_nano_diamond')
        .dust()
        .color(0x59fbff)
        .iconSet('diamond')
        .element('carbon')
        .formula('C⁺⁺')
    event.create('superfluid_helium')
        .liquid(4)
        .color(0xe9edc2)
        .element(GTElements.He3)
    event.create('stabilized_naquadria_plasma')
        .plasma(5000)
        .color(0x43b574)
        .element(GTElements.Nq2)
    event.create('unprocessed_nanothermal_fluid')
        .liquid(3)
        .color(0xb2e349)
    event.create('ion_implanted_nanothermal_fluid')
        .liquid(3)
        .color(0x44dba6)
    event.create('pcb_coolant_mk2')
        .liquid(2)
        .color(0x400bb3)
    event.create('overheated_blaze')
        .liquid(6000)
        .color(0xdbad14)
    event.create('excited_blaze_concentate')
        .liquid(8000)
        .color(0xe6b000)
    event.create('chronon')
        .gem()
        .ore(1, 1,)
        .element('chronon')
        .iconSet('opal')
        .color(0x9be8e3)
    event.create('synchronized_chronon')
        .gem()
        .element('chronon')
        .formula('Cn⇄')
        .iconSet('opal')
        .color(0x4de8de)
        .flags(GTMaterialFlags.GENERATE_LENS)
    event.create('silicon_tetrachloride')
        .liquid(330)
        .color(0x9d82b8)
        .components('1x silicon', '4x chlorine')
    event.create('tetraethyl_orthosilicate')
        .liquid(334)
        .color(0x9bccb3)
        .components('1x silicon', '8x carbon', '20x hydrogen', '4x oxygen')
    event.create('silver_nitrate_solution')
        .liquid(483)
        .color(0xc1ced6)
        .components('1x silver', '1x nitrogen', '3x oxygen')
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)
    event.create('nanoreinforced_silver')
        .dust()
        .color(0xa3a29d)
        .iconSet('shiny')
        .element(GTElements.Ag)
        .formula('Ag⁺')
    event.create('sodium_iodine')
        .dust()
        .color(0x634c8a)
        .components('1x sodium', '1x iodine')
    event.create('sodium_iodate')
        .dust()
        .color(0x857999)
        .components('1x sodium', '1x iodine', '3x oxygen')
        .flags(GTMaterialFlags.DECOMPOSITION_BY_ELECTROLYZING)
    event.create('thallium_iodine')
        .dust()
        .color(0xfcf03d)
        .components('1x thallium', '1x iodine')
    event.create('thallium_doped_sodium_iodine')
        .gem()
        .color(0x585163)
        .components('1x sodium', '1x iodine', '1x thallium')
        .formula('NaI(Tl)', true)
        .flags(GTMaterialFlags.GENERATE_LENS, GTMaterialFlags.DISABLE_DECOMPOSITION)  
    event.create('tachyon_condensate')
        .liquid(10)
        .color(0xb519ad)
        .formula('T', true)
    event.create('spatial_flux')
        .liquid(6)
        .color(0x530691)
    event.create('stabilized_spatial_flux')
        .liquid(6)
        .color(0x903ad6)
    event.create('temporal_flux_mixture')
        .liquid(5)
        .color(0x34bfed)
    event.create('stabilized_temporal_flux_mixture')
        .liquid(3)
        .color(0xd4f4ff)
    event.create('time_looped_flux')
        .liquid(2)
        .color(0xeda8ec)
    event.create('reverse_temporal_flux')
        .liquid(2)
        .color(0x9ade8a)
    event.create('pcb_coolant_mk3')
        .liquid(1)
        .color(0xdb5a96)









/// C O S M I C   M A T E R I A L S   F U S I O N
    
event.create('cosmic_tungsten')
.ingot().liquid()
.ore(1, 1,)
.element('cosmic_tungsten')
.color(0x04011c)
.iconSet('radioactive')
.blastTemp(13000, 'highest', 8388608, 900)
.flags(
    GTMaterialFlags.GENERATE_PLATE, 
    GTMaterialFlags.GENERATE_ROD, 
    GTMaterialFlags.GENERATE_GEAR, 
    GTMaterialFlags.GENERATE_FINE_WIRE,
    GTMaterialFlags.GENERATE_FRAME, 
    GTMaterialFlags.GENERATE_DENSE, 
    GTMaterialFlags.GENERATE_ROTOR, 
    GTMaterialFlags.GENERATE_BOLT_SCREW,
    GTMaterialFlags.GENERATE_SMALL_GEAR,
    GTMaterialFlags.GENERATE_LONG_ROD,
    GTMaterialFlags.GENERATE_ROUND
)
event.create('cosmic_titanium')
.ingot().liquid()
.ore(1, 1,)
.element('cosmic_titanium')
.color(0x3d0245)
.iconSet('radioactive')
.blastTemp(13000, 'highest', 8388608, 900)
.flags(
    GTMaterialFlags.GENERATE_PLATE, 
    GTMaterialFlags.GENERATE_ROD, 
    GTMaterialFlags.GENERATE_GEAR, 
    GTMaterialFlags.GENERATE_FINE_WIRE,
    GTMaterialFlags.GENERATE_FRAME, 
    GTMaterialFlags.GENERATE_DENSE, 
    GTMaterialFlags.GENERATE_ROTOR, 
    GTMaterialFlags.GENERATE_BOLT_SCREW,
    GTMaterialFlags.GENERATE_SMALL_GEAR,
    GTMaterialFlags.GENERATE_ROUND,
    GTMaterialFlags.GENERATE_LONG_ROD
)
event.create('cosmic_iridium')
.ingot().liquid()
.ore(1, 1,)
.element('cosmic_iridium')
.color(0x016646)
.iconSet('radioactive')
.blastTemp(13000, 'highest', 33554432, 900)
.flags(
    GTMaterialFlags.GENERATE_PLATE, 
    GTMaterialFlags.GENERATE_ROD, 
    GTMaterialFlags.GENERATE_GEAR, 
    GTMaterialFlags.GENERATE_FINE_WIRE,
    GTMaterialFlags.GENERATE_FRAME, 
    GTMaterialFlags.GENERATE_DENSE, 
    GTMaterialFlags.GENERATE_ROTOR, 
    GTMaterialFlags.GENERATE_BOLT_SCREW,
    GTMaterialFlags.GENERATE_SMALL_GEAR,
    GTMaterialFlags.GENERATE_ROUND,
    GTMaterialFlags.GENERATE_LONG_ROD
)
event.create('cosmic_osmium')
.ingot().liquid()
.ore(1, 1,)
.element('cosmic_osmium')
.color(0x023e45)
.iconSet('radioactive')
.blastTemp(13000, 'highest', 8388608, 900)
.flags(
    GTMaterialFlags.GENERATE_PLATE, 
    GTMaterialFlags.GENERATE_ROD, 
    GTMaterialFlags.GENERATE_GEAR, 
    GTMaterialFlags.GENERATE_FINE_WIRE,
    GTMaterialFlags.GENERATE_FRAME, 
    GTMaterialFlags.GENERATE_DENSE, 
    GTMaterialFlags.GENERATE_ROTOR, 
    GTMaterialFlags.GENERATE_BOLT_SCREW,
    GTMaterialFlags.GENERATE_LONG_ROD,
    GTMaterialFlags.GENERATE_SMALL_GEAR,
    GTMaterialFlags.GENERATE_ROUND
)


event.create("universium")
.liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
.ingot()
.element(GTElements.get("universium"))
.color(0xffffff)
.iconSet('universium')
.flags(
    GTMaterialFlags.GENERATE_PLATE, 
    GTMaterialFlags.GENERATE_ROD, 
    GTMaterialFlags.GENERATE_GEAR, 
    GTMaterialFlags.GENERATE_FINE_WIRE,
    GTMaterialFlags.GENERATE_DENSE, 
    GTMaterialFlags.GENERATE_ROTOR, 
    GTMaterialFlags.GENERATE_BOLT_SCREW,
    GTMaterialFlags.GENERATE_SMALL_GEAR,
    GTMaterialFlags.GENERATE_ROUND,
    GTMaterialFlags.GENERATE_SPRING,
    GTMaterialFlags.GENERATE_FRAME
)
event.create("eternity")
.liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
.ingot()
.element(GTElements.get("eternity"))
.color(0xffffff)
.iconSet('eternity')
.flags(
    GTMaterialFlags.GENERATE_PLATE, 
    GTMaterialFlags.GENERATE_ROD, 
    GTMaterialFlags.GENERATE_GEAR, 
    GTMaterialFlags.GENERATE_FINE_WIRE,
    GTMaterialFlags.GENERATE_DENSE, 
    GTMaterialFlags.GENERATE_ROTOR, 
    GTMaterialFlags.GENERATE_BOLT_SCREW,
    GTMaterialFlags.GENERATE_SMALL_GEAR,
    GTMaterialFlags.GENERATE_ROUND,
    GTMaterialFlags.GENERATE_SPRING,
    GTMaterialFlags.GENERATE_FRAME
)
event.create("molten_space_time")
.liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
.color(0xffffff)
event.create('space_time')
.ingot()
.element('space_time')
.color(0xffffff)
.iconSet('space_time')
.flags(
    GTMaterialFlags.GENERATE_PLATE,
    GTMaterialFlags.GENERATE_ROD,
    GTMaterialFlags.GENERATE_LONG_ROD,
    GTMaterialFlags.GENERATE_RING,
    GTMaterialFlags.GENERATE_ROUND,
    GTMaterialFlags.GENERATE_GEAR, 
    GTMaterialFlags.GENERATE_SMALL_GEAR,
    GTMaterialFlags.GENERATE_SPRING, 
    GTMaterialFlags.GENERATE_BOLT_SCREW, 
    GTMaterialFlags.PHOSPHORESCENT
)

event.create("stellar_matter_plasma")
.liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
.ingot()
.element(GTElements.get("stellar_matter_plasma"))
.color(0xffffff)
.iconSet('stellar_matter')
.flags(
    GTMaterialFlags.GENERATE_PLATE, 
    GTMaterialFlags.GENERATE_ROD, 
    GTMaterialFlags.GENERATE_GEAR, 
    GTMaterialFlags.GENERATE_FINE_WIRE,
    GTMaterialFlags.GENERATE_DENSE, 
    GTMaterialFlags.GENERATE_ROTOR, 
    GTMaterialFlags.GENERATE_BOLT_SCREW,
    GTMaterialFlags.GENERATE_SMALL_GEAR,
    GTMaterialFlags.GENERATE_ROUND,
    GTMaterialFlags.GENERATE_SPRING,
    GTMaterialFlags.GENERATE_FRAME

)



// COSMIC LINE

event.create("raw_cosmic_matter")
.gas()
.color(0x000000)
event.create("crude_astral_flux")
.plasma()
.color(0x2c00ad)
event.create("astral_flux") 
.plasma()
.color(0x4000ff)
.element('astral_flux')
event.create("hyper_ionized_helium")
.plasma()
.color(0xfff2ab)
.formula('He⁺', true)
event.create("infused_cosmic_matter")
.gas()
.color(0xaeabff)
event.create("stabilized_raw_cosmic_matter")
.gas()
.color(0x14004f)
event.create("cryo_compressed_raw_cosmic_matter")
.gas()
.color(0x00224f)
event.create("cryogenic_neutron_flow")
.liquid()
.color(0x00fff7)
event.create("shifted_cosmic_matter_base")
.gas()
.color(0x020078)
event.create("plasma_tempered_cosmic_matter_base")
.plasma()
.color(0x060040)
event.create("hyper_dense_cosmic_matter_base")
.plasma()
.color(0x020012)
event.create("refined_cosmic_matter")
.plasma()
.color(0x1c00ff)
event.create("cosmic_matter")
.liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
.element(GTElements.get("cosmic_matter"))
.color(0xffffff)
event.create("pure_cosmic_matter")
.ingot()
.element(GTElements.get("cosmic_matter"))
.color(0xffffff)
.iconSet('cosmic_matter')
.flags(
    GTMaterialFlags.GENERATE_PLATE, 
    GTMaterialFlags.GENERATE_ROD, 
    GTMaterialFlags.GENERATE_GEAR, 
    GTMaterialFlags.GENERATE_FINE_WIRE,
    GTMaterialFlags.GENERATE_DENSE, 
    GTMaterialFlags.GENERATE_ROTOR, 
    GTMaterialFlags.GENERATE_BOLT_SCREW,
    GTMaterialFlags.GENERATE_SMALL_GEAR,
    GTMaterialFlags.GENERATE_ROUND,
    GTMaterialFlags.GENERATE_SPRING,
    GTMaterialFlags.GENERATE_FRAME
)
 
// PLASMAS NEBULA

event.create("hypercharged_nebular") 
.plasma()
.color(0x1c03fc)
.element('nebular_matter')
event.create("high_entropy_neptunium") 
.plasma()
.color(0x03a1fc)
.element(GTElements.Np)
event.create("supercritical_californium") 
.plasma()
.color(0xffffff)
.element(GTElements.Cf)
event.create("hypercharged_oganesson") 
.plasma()
.color(0xa39672)
.element(GTElements.Og)
event.create("hypercharged_nihonium") 
.plasma()
.color(0x84a1e8)
.element(GTElements.Nh)

event.create("quark_gluon")
    .plasma()
    .color(0xc7cdcdd)
event.create("degenerate_gluon_condensate")
    .liquid()
    .color(0xf7d0ed)

event.create("astral_space_time_plasma")
.liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
.components('1x astral_flux', '1x space_time')
.flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

event.create("chrono_infinity")
.ingot()
.liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
.cableProperties(8589934592, 9999, 0, true)
.blastTemp(17000, 'highest', 536870912, 1800)
.element(GTElements.get("chrono_infinity"))
.color(0xffffff)
.iconSet('chrono-infinity_alloy')
.flags( 
    GTMaterialFlags.GENERATE_FOIL, 
    GTMaterialFlags.GENERATE_GEAR, 
    GTMaterialFlags.GENERATE_SMALL_GEAR,
    GTMaterialFlags.GENERATE_DENSE, 
    GTMaterialFlags.GENERATE_RING, 
    GTMaterialFlags.GENERATE_PLATE,
    GTMaterialFlags.GENERATE_ROD,
    GTMaterialFlags.GENERATE_LONG_ROD,
    GTMaterialFlags.GENERATE_ROTOR,
    GTMaterialFlags.GENERATE_BOLT_SCREW,
    GTMaterialFlags.GENERATE_ROUND,
    GTMaterialFlags.GENERATE_SPRING,
    GTMaterialFlags.GENERATE_SPRING_SMALL,
    GTMaterialFlags.GENERATE_FINE_WIRE,
    GTMaterialFlags.GENERATE_FRAME
)

 // Kerosene Line

 	event.create('high_purity_kerosene')
        .liquid()
        .color(0xe6daba)
 	event.create('aromatic_byproduct')//byproduct
        .dust()
        .color(0x4d047a)
    event.create('wax_free_high_purity_kerosene')
        .liquid()
        .color(0xe8e0cc)
    event.create('paraffin_wax')//byproduct
        .dust()
        .color(0xf7dc99)
    event.create('supercritical_carbon_dioxide')
        .liquid()
        .color(0xaed6d6)
        .formula('CO₂↔', true)
    event.create('fluoropolymer_solution')
        .dust()
        .color(0x646969)
    event.create('thermal_conductivity_additive')
        .dust()
        .color(0x878701)
    event.create('antioxidant_complex')
        .liquid()
        .color(0x96473b)
    event.create('precursor_suspension')
        .liquid()
        .color(0x995f56)
    event.create('precursor_thermal_blend')
        .liquid()
        .color(0x998756)
    event.create('refined_thermal_blend')
        .dust()
        .color(0x9c6e41)
    event.create('heavy_benzene')
        .liquid()
        .color(0x0f0f0f)
    event.create('quantum_activated_thermal_blend')
        .dust()
        .color(0xb8821f)
    event.create('kerosene_based_heating_fluid')
        .liquid()
        .color(0xf5e967)
    event.create('hydrogen_plasma')
        .plasma()
        .color(0x0a1afa)
        .element(GTElements.H)
    event.create('neon_plasma')
        .plasma()
        .color(0xffc7cb)
        .element(GTElements.Ne)

    event.create('neutron_flux')
        .plasma()
        .color(0xdefff7)
    event.create('exotic_particle_suspension')
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    event.create('iridium_plasma')
        .plasma()
        .color(0x45f7e0)
        .element(GTElements.Ir)
    event.create('osmium_plasma')
        .plasma()
        .color(0x132ec2)
        .element(GTElements.Os)
    event.create('annihilation_residue')
        .dust()
        .color(0x4b0794)
    event.create('plutonium_239_plasma')
        .plasma()
        .color(0xff0000)
        .element(GTElements.Pu239)
    event.create('tungsten_plasma')
        .plasma()
        .color(0x1f1d1d)
        .element(GTElements.W)
    event.create('temporally_charged_silicon')
        .ingot()
        .blastTemp(17000, 'highest', 134217728, 900)
        .element('temporally_charged_silicon')
        .color(0xbdbbbb)
        .flags(
        GTMaterialFlags.GENERATE_PLATE, 
        GTMaterialFlags.GENERATE_ROD, 
        GTMaterialFlags.GENERATE_GEAR, 
        GTMaterialFlags.GENERATE_FINE_WIRE,
        GTMaterialFlags.GENERATE_DENSE, 
        GTMaterialFlags.GENERATE_ROTOR, 
        GTMaterialFlags.GENERATE_BOLT_SCREW,
        GTMaterialFlags.GENERATE_SMALL_GEAR,
        GTMaterialFlags.GENERATE_ROUND,
        GTMaterialFlags.GENERATE_SPRING,
        GTMaterialFlags.GENERATE_FRAME
        )
    event.create('exotic_condensate')
        .dust()
        .color(0x3b0aff)
    event.create('refined_exotic_condensate')
        .dust()
        .color(0x3503fc)
    event.create('decay_stabilized')
        .plasma()
        .color(0x23195e)

    event.create('solar_eclipse_alloy')
        .ingot()
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .iconSet('solar_eclipse_alloy')
        .blastTemp(13500, 'highest', 1966080, 3400)
        .element('solar_eclipse_alloy')
        .flags(
        GTMaterialFlags.GENERATE_PLATE, 
        GTMaterialFlags.GENERATE_ROD, 
        GTMaterialFlags.GENERATE_GEAR, 
        GTMaterialFlags.GENERATE_FINE_WIRE,
        GTMaterialFlags.GENERATE_DENSE, 
        GTMaterialFlags.GENERATE_ROTOR, 
        GTMaterialFlags.GENERATE_BOLT_SCREW,
        GTMaterialFlags.GENERATE_SMALL_GEAR,
        GTMaterialFlags.GENERATE_ROUND,
        GTMaterialFlags.GENERATE_SPRING,
        GTMaterialFlags.GENERATE_FRAME
        )

    event.create('solar_radiation_alloy')
        .ingot()
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .iconSet('solar_radiation_alloy')
        .element('solar_radiation_alloy')
        .flags(
        GTMaterialFlags.GENERATE_PLATE, 
        GTMaterialFlags.GENERATE_ROD, 
        GTMaterialFlags.GENERATE_GEAR, 
        GTMaterialFlags.GENERATE_DENSE, 
        GTMaterialFlags.GENERATE_ROTOR, 
        GTMaterialFlags.GENERATE_BOLT_SCREW,
        GTMaterialFlags.GENERATE_SMALL_GEAR,
        GTMaterialFlags.GENERATE_ROUND,
        GTMaterialFlags.GENERATE_SPRING,
        GTMaterialFlags.GENERATE_FRAME
        )
       
    event.create('proto_matter')
        .ingot()
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .iconSet('proto_matter')
        .element('proto_matter')
        .flags(
        GTMaterialFlags.GENERATE_PLATE, 
        GTMaterialFlags.GENERATE_ROD, 
        GTMaterialFlags.GENERATE_GEAR, 
        GTMaterialFlags.GENERATE_FINE_WIRE,
        GTMaterialFlags.GENERATE_DENSE, 
        GTMaterialFlags.GENERATE_ROTOR, 
        GTMaterialFlags.GENERATE_BOLT_SCREW,
        GTMaterialFlags.GENERATE_SMALL_GEAR,
        GTMaterialFlags.GENERATE_ROUND,
        GTMaterialFlags.GENERATE_SPRING,
        GTMaterialFlags.GENERATE_FRAME
        )
        

    })